//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INAIPI.Core.AdminApp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.8.0.0")]
    internal sealed partial class Log4net : global::System.Configuration.ApplicationSettingsBase {
        
        private static Log4net defaultInstance = ((Log4net)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Log4net())));
        
        public static Log4net Default {
            get {
                return defaultInstance;
            }
        }
    }
}
